version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    branches:
      ignore:
        - gh-pages
    working_directory: ~/xiaomi-push
    steps:
      - checkout
      - run: bundle install
      - run: rake spec
